#!/bin/sh

buf=""
for var in PG_HOST PG_PORT PG_PASSWORD \
    SCRAPY_DB_NAME SCRAPY_DB_USER SCRAPY_DB_PASSWORD \
    DOCCANO_DB_NAME DOCCANO_DB_USER DOCCANO_DB_PASSWORD \
    MEDCAT_DB_NAME MEDCAT_DB_USER MEDCAT_DB_PASSWORD \
    DATADICT_DB_NAME DATADICT_DB_USER DATADICT_DB_PASSWORD \
; do
    buf=" $buf --env $var"
done

docker run $buf db-init
