# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class BaseItem(scrapy.Item):
    """Base class for items generated by scrapers. The framework ignores any items that are not instances of this class"""
    source_url = scrapy.Field() # Mandatory field. See ../../README.md for details.
    retrieved_at = scrapy.Field() # Optional field. Currently not used.
    modified_at = scrapy.Field() # Optional field. Should not be set in case of multiple documents on the same page.


class CorpusItem(BaseItem):
    """Base class for corpus text items."""
    pass


class TextItem(CorpusItem):
    """A corpus item in plain text format"""
    text = scrapy.Field()


class HTMLItem(CorpusItem):
    """A corpus item in html format. The framework converts this to plain text before ingesting"""
    html = scrapy.Field()


class DataDictionaryItem(BaseItem):
    item_type = scrapy.Field()
    item_id = scrapy.Field()
    name = scrapy.Field()
    description = scrapy.Field()
    links = scrapy.Field()
    meta = scrapy.Field()
